name: Go
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  PR_NUMBER: ${{ github.event.number }}
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ADD PR NUMBER
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER_PAYLOAD', prNumber);


      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: clean cache
        run: |
          go clean --modcache
          go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.5.0
          go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.5.0
          go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Test Go
        run: |
          ginkgo -r --junit-report=./test-report.xml
      - name: Foresight Action
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.F_STAGING_API_KEY }}
          test_framework: JUNIT
          test_path: ./test-report.xml
