name: Go
on:
  issue_comment:
    types:
      - created
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:


env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  PR_NUMBER: ${{ github.event.number }}

jobs:
 
